### ISSUE TITLE
stand-alone

### ISSUE THREAD

**Issue by spicyjuice** [AlessandroZ/BeRoot#19]
Hey, first of all congrats on this awsome proj!
in order to run the script on target systems i'm packaging it in a zip and renaming beroot.py to __main__.py (the linux version), so that i can run `python beroot.zip` as a standalone.
it can be useful in case you can't run it with pupy, which is my scenario

**Comment by AlessandroZ** [comment]
Hi, sorry for my late answer. 
Why don't you download the repo from github and run it using python ? 
```
wget https://github.com/AlessandroZ/BeRoot/archive/master.zip
unzip master.zip
cd BeRoot-master/Linux/
python beroot.py
```

Does not need to be launched from pupy.

**Comment by spicyjuice** [comment]
That's actually an easier solution! During a pentest i prefer to have standalone "executables", without the need of extracting anything is possible, that was my reasoning behind the zip.
Thanks for the answer

P.s. how did you compile it? because i'm having issues with pyinstaller
