### ISSUE TITLE
32-bits pre-compiled binary

### ISSUE THREAD

**Issue by voidpt** [AlessandroZ/BeRoot#2]
There is only a 64-bits pre-compiled version of the tool on https://github.com/AlessandroZ/BeRoot/releases/download/1.0/beRoot.zip .

It would be great to have 32-bits too.
Did you use py2exe for binary compilation?

**Comment by AlessandroZ** [comment]
Here it is : https://github.com/AlessandroZ/BeRoot/releases/tag/1.0.1
