### ISSUE TITLE
[Chore] setup.py

### ISSUE THREAD

**Issue by noraj** [AlessandroZ/BeRoot#28]
Hi,

Could you provide a setup.py please?

Python packaging
  
  - [Packaging Python Projects - setup.py](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py)
  - [Packaging and distributing projects](https://packaging.python.org/guides/distributing-packages-using-setuptools/)
  - [Command Line Scripts](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html)

**Comment by AlessandroZ** [comment]
Hi @noraj, 

Sorry but I don't understand the purpose of your request. On linux you just need to copy the project and run beroot. No prerequis are needed. 
Do I miss something ?

**Comment by noraj** [comment]
I was making batch issues for python package without a setup.py that are to be included in BlackArch repository.
But in the specific case of beroot, which is made to be copied on a target machine, I guess it's not useful as it could be for a tool meant to be used on a pentester machine.
Sorry, consider this issue a false positive.

**Comment by AlessandroZ** [comment]
Ok, no problem :)
